### PR TITLE
Refactor and coverage

### PR DESCRIPTION
**Pull request by vladistan**
Hi,

    I refactored some of overly complex functions and added more unit tests.

### CODE REVIEW

**Comment by vladistan** [comment]
Looks like it's failing on python 2.6 because it doesn't support some unit test assertions.

Let me fix that..

**Comment by vladistan** [comment]
Glad you like it.    My toolset consist of  Sonar to identify issues  (over complex methods, etc) and PyCharm for refactoring.   Although PyCharm doesn't help as much because Python is hard to refactor due to it's dynamic nature.  So,  most of refactoring is done by hand.

**Comment by rbrito** [comment]
What is this sonar thing? Is it this: http://docs.codehaus.org/display/SONAR/Python+Plugin (?) or something else?

**Comment by vladistan** [comment]
Yes

Essentilly it is just a front-end for the pylint and friends with somewhat nice web interface.  Main reason I like it is that it measure code complexity.  Overly complex functions are know to be sources of bugs.

	— Vlad

**Comment by rbrito** [comment]
Hi, Vlad.

On Feb 23 2015, Vlad Korolev wrote:
> Essentilly it is just a front-end for the pylint and friends with somewhat
> nice web interface.

You've piqued my interest with this. I am using pylint (and pychecker and
pyflakes) as all of them are available on Debian, but I didn't know about
sonar.

I'm very much into anything (static analyzers, code coverage tools etc.)
that can help improve the quality of our code, since the codebase only gets
more complex with time.

One thing that I have not yet used with coursera-dl is a profiling tool and
I noticed that our test suite runs *much* faster with Python 3 than with
Python 2.

I will take a look into this sonar thing.

> Main reason I like it is that it measure code complexity.  Overly complex
> functions are know to be sources of bugs.

Sure. Since I started contributing to this, this was one of my main
motivations.

Oh, BTW, if you can extract more code into functions (whenever reasonable),
please, go ahead and send me a pull request.


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Pull request merged**
