### PR TITLE
Updates to the setup.py script

### PR DESCRIPTION
**Pull request by rbrito**
The current version of the `setup.py` script that we have doesn't seem to be functional (yet).

In particular, the entry point scripts don't seem to get included in the source package. I don't know if they are supposed to (or if they get created upon installation), but with these two commits, they *do* seem to be created.

Since I am not entirely sure of the recommended procedure, I'd appreciate some peer-review on this pull request of mine, especially from people who convinced me that we should distribute the program via PyPi. :)

@meejah, @FedericoCeratto, @vladistan, @mshytikov, any comments here?

Thanks a lot for your wisdom,

Rogério.

### CODE REVIEW

**Comment by rbrito** [comment]
Apparently, the entry point script *does* get created automatically when doing a `bdist`, at least on my Debian box. I suppose that it should do the same on a Windows box, but I don't have any windows machine to which I have access.

This probably means that I should revert my commit f641cc5bf0e35dd613be09bd97143ef5347311f7, but I am still interested in getting comments about the file in general. :)

Thanks,

Rogério.

**Comment by FedericoCeratto** [comment]
see the release task in fabfile.py.
"fab release" should do the trick.

**Comment by meejah** [comment]
Yes, "entry-points" will create magic scripts on different platforms (e.g. you get a ``.bat`` on windows, I believe).

**Comment by rbrito** [comment]
Hi, @meejah.

On Apr 27 2015, meejah wrote:
> Yes, "entry-points" will create magic scripts on different platforms
> (e.g. you get a ``.bat`` on windows, I believe).

Yes, I discovered that after I created an sdist and it was incomplete
(lacking the files that the setup.py reads).

After I created a MANIFEST.in (which I committed), the sdist can be
installed and I think that we can finally have our first release on PyPI.
:)

That's progress. ;) There are many things to improve, and I would appreciate
if you could take a look at the last few commits:

    https://github.com/coursera-dl/coursera/commits/master

As you can see, I tend to be a bit verbose on my commit messages (which I
think is a good practice that I acquired by reading commits from the Linux
kernel).  So, it should be easy to follow my line of thinking, I hope. :)

As you can see, I am a real novice with the tooling of Python, but I'm
learning. :)


Anyway, thanks for the confirmation,

Rogério Brito.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Hi.

On Apr 26 2015, Federico Ceratto wrote:
> see the release task in fabfile.py.
> "fab release" should do the trick.

Thanks, but this didn't quite answer what I was looking for.

I did try to run "python setup.py sdist" manually (I didn't want to prepare
all the things for a release, like tagging stuff, as it was and may still be
far from done), and the problem was that the mere installation of the
tarball created by sdist is (at least for me) not working.

Did it work for you?


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by meejah** [comment]
I see. I'll take a closer look. An "sdist" tarball would be similar to downloading the source -- someone *should* be able to do "python setup.py install" from it and get a working thing. Likely something missing from MANIFEST.in or so. I should have time in the next couple days.

**Comment by rbrito** [comment]
Hi, @meejah.

On Apr 27 2015, meejah wrote:
> I see. I'll take a closer look. An "sdist" tarball would be similar to
> downloading the source

That's the missing explicit information that I didn't know (and the reason
why I created this pull request asking for comments). I will include other
files in the MANIFEST.in, then, like the LICENSE file.

Unfortunately, it seems that setup.py doesn't know about README.md (while it
does for other extensions for a README file), so I had to explicitly include
it in the manifest file.

Just one question: do the test files belong in an sdist tarball?

> someone *should* be able to do "python setup.py install" from it and get a
> working thing. Likely something missing from MANIFEST.in or so.

Thanks for the confirmation.

> I should have time in the next couple days.

I really appreciate it. Even though I won't be merging the code in this pull
request, I feel that your comments have already fulfilled my intention with
it and I hope that your review of the basic distribution of the code will
create a better 1st release for us.

It's late right now and I'm heading to bed, but I will add a few files to
the MANIFEST.in file.

I will also convert more of the tests to pytest, but that's material for a
different thread. :)


Thanks once again,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
I deleted this branch now, as I think that I got a clearer idea of what the `setup.py` script and its companion files should do, thanks to @meejah's guidance.

I would still appreciate if anybody could review the script and make sure that what can be generated with it can be (independently) installed. This way, I would feel more confident in publishing the first release of our project to PyPI. :)

**Pull request closed without merging**
