### PR TITLE
Added setup.py

### PR DESCRIPTION
**Pull request by mshytikov**
Hi 

I have created the simple `setup.py` to improve installation process via packaging.
The coursera-dl can be submitted to PyPi and the installation for end user will be much simpler:
```pip install coursera-dl``` (all dependencies will be installed automatically)
and the usage will be - 'you can run command `coursera-dl ...`  from any directory and without worrying of PATH variable'

While it is not yet available on PyPi it can be built and installed locally.
to build a package:
```python setup.py build sdist```
to install it:
```pip install dist/coursera-dl-*.tar.gz``` 

P.S. The only thing which can be potentially broken is a Windows support.

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
@rbrito: coursera-dl is very nice - if you could include this pull request and #303 in the next release I could try to get it packaged in Debian (and its derivatives) :)

**Comment by rbrito** [comment]
Dear Max,

Thank you so very much for this pull request. We now have a `setup.py` with (at least my changes) inspired on your work.

As a result, I am closing this pull request. I guess that we need an authors file to credit all our contributors...

(A few moments later...)

I have just cherry picked one of your commits and I created an `AUTHORS.md` file. Feel free to send a pull request with your name, if you'd like.

**Comment by mshytikov** [comment]
Waw Guys, you did a great job, congratulation! 
Thank you!

Dear @rbrito 
Sorry for the late reply I was offline for a long time.
The current ```setup.py``` looks much better! 
Thank you for your effort you put through to make this happen!

**Comment by Make42** [comment]
Dear @mshytikov and @rbrito 
Is there an installation instruction how to setup the docker besides the posts in https://github.com/coursera-dl/coursera/issues/344 ? I get that you somehow integrated the docker into coursera-dl, but how do we take advantage of this?

**Comment by mshytikov** [comment]
Dear @Make42 

> I get that you somehow integrated the docker into coursera-dl, but how do we take advantage of this?

Actually the advantage is small. If you have a proper setup for your python environment then I would say it is better to install coursera via pip  ```pip install coursera```. 
But in case if you are familiar with docker or you have a problem with using coursera-dl on your machine then you can use docker. 

> Is there an installation instruction how to setup the docker besides the posts in #344

The Docker installation instruction is OS dependent, please find it here https://docs.docker.com/installation/

For [example](https://goo.gl/104PaM) for me the simplest way is to use Vagrant with docker provisioner. 
But in this case you need [Vagrant](http://www.vagrantup.com/downloads.html) ( and probably [VirtualBox](https://www.virtualbox.org/wiki/Downloads) ) to be installed on your system.

**Pull request closed without merging**
